#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'compareTriplets' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def compareTriplets(a, b):
    alice = 0;
    bob = 0;
    scores=[alice,bob]
    for i in range(3):
        if(a[i]!=a[b]):
            if(a[i]>b[i]):
                
                
    return scores
    # Write your code here
