#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'compareTriplets' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def compareTriplets(a, b):
    alice = 0;
    bob = 0;
    scores=[alice,bob]
    for i in range(3):
        if(a[i]!=b[i]):
            if(a[i]>b[i]):
                alice+=1
            else:
                bob+=1
    scores=[alice,bob]                
    return scores
    # Write your code here

print(compareTriplets([1,0,0], [0,1,1]))
